config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    path(
        "", room_views.HomeView.as_view(), name="home"
    ),  # function이 아닌, class based view에선 as_view()를 사용
    # path("", room_views.all_rooms, name="home"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path(
        "login/github/callback",
        views.github_callback,
        name="github-callbacklogin",
    ),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path(
        "login/kakao/callback",
        views.kakao_callback,
        name="kakao-callbacklogin",
    ),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500 flex flex-col">
    <span>
        Please don't copy us.
    </span>
    <span>&copy; 2019 Nomad Coders. All rights reserved.</span>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-sm font-medium h-full">
  {% if user.is_authenticated %}
    <li class="ml-8"><a href="{% url 'users:logout' %}">Log out</a></li>
  {% else %}
    <li class="nav_link"><a href="{% url 'users:login' %}">Log in</a></li>
    <li class="nav_link"><a href="{% url 'users:signup' %}">Sign up</a></li>
  {% endif %}

</ul>
{% comment %}
<form method="get" action="{% url 'rooms:search' %}">
  <input value="Seoul" name="city" placeholder="Search by City" />
</form>
{% endcomment %}

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn border-2  text-gray-700 mb-2 border-gray-700">
        <i class="fab fa-github-alt mr-2 fa-lg"></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}"
        class="w-full border font-medium text-yellow-800 mb-2 border-yellow-400 text-center rounded-sm py-5 bg-yellow-400 ">
            <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
        </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-3 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>